---
version: '3.6'

services:
  prometheus:
    image: "prom/prometheus"
    volumes:
      - ./common/config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus:/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090/tcp
    networks:
      quorum-benchmark:
        ipv4_address: 172.16.239.32

  grafana:
    image: "grafana/grafana"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_USERS_VIEWERS_CAN_EDIT=true
    volumes:
      - ./common/config/grafana/provisioning/:/etc/grafana/provisioning/
      - grafana:/var/lib/grafana
    ports:
      - 3000:3000/tcp
    networks:
      quorum-benchmark:
        ipv4_address: 172.16.239.33

  chaos-pause:
    image: gaiaadm/pumba
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: "--log-level debug --interval 30s --random pause --duration 10s re2:^network-validator"

  chaos-delay:
    image: gaiaadm/pumba
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: "--log-level debug --interval 10s --random netem --tc-image gaiadocker/iproute2 --duration 6s delay re2:^network-validator"

networks:
  quorum-benchmark:
    name: quorum-benchmark
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.16.239.0/24

volumes:
  prometheus:
  grafana:
