bankArgs: &bank-args
  initialMoney: 10000
  moneyToTransfer: 100
  numberOfAccounts: &number-of-accounts 1000

monitors:
  resource:
    - module: docker
      options:
        interval: 5
        containers:
          - all
        charting:
          bar:
            metrics: [ Memory(avg), CPU%(avg) ]
test:
  name: bank
  description: >-
    This is an example benchmark for Caliper, to test the backend DLT's
    performance with simple account opening & querying transactions.
  workers:
    number: 1
  rounds:
    - label: open
      description: >-
        Test description for the opening of an account through the deployed
        contract.
      txNumber: *number-of-accounts
      rateControl:
        type: fixed-rate
        opts:
          tps: 50
      workload:
        module: benchmarks/scenario/bank-private/open.js
        arguments: *bank-args
    - label: query
      description: Test description for the query performance of the deployed contract.
      txNumber: *number-of-accounts
      rateControl:
        type: fixed-rate
        opts:
          tps: 100
      workload:
        module: benchmarks/scenario/bank-private/query.js
        arguments: *bank-args
    - label: transfer
      description: Test description for transferring money between accounts.
      txNumber: 50
      rateControl:
        type: fixed-rate
        opts:
          tps: 5
      workload:
        module: benchmarks/scenario/bank-private/transfer.js
        arguments:
          << : *bank-args
          money: 100
