bankArgs: &bank-args
  initialMoney: 10000
  moneyToTransfer: 1000
  numberOfAccounts: &number-of-accounts 100

rateControl: &rate
  type: fixed-rate
  opts:
    tps: 20

monitors:
  resource:
    - module: docker
      options:
        interval: 5
        containers:
          - all
        charting:
          bar:
            metrics: [ Memory(avg), CPU%(avg) ]
test:
  name: bank
  description: >-
    This is an example benchmark for Caliper, to test the backend DLT's
    performance with simple account opening & querying transactions.
  workers:
    number: 4
  rounds:
    - label: open
      description: >-
        Test description for the opening of an account through the deployed
        contract.
      txNumber: *number-of-accounts
      rateControl: *rate
      workload:
        module: benchmarks/scenario/bank-public/open.js
        arguments: *bank-args
    - label: query
      description: Test description for the query performance of the deployed contract.
      txNumber: *number-of-accounts
      rateControl: *rate
      workload:
        module: benchmarks/scenario/bank-public/query.js
        arguments: *bank-args
    - label: transfer
      description: Test description for transferring money between accounts.
      txNumber: 100
      rateControl: *rate
      workload:
        module: benchmarks/scenario/bank-public/transfer.js
        arguments:
          << : *bank-args
          money: 100
